{{- if .Values.addons.metallb }}
{{- if .Values.addons.metallb.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: metallb-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "metallb"
  repoName: "extra-charts"
  releaseName: "metallb"
  version: 0.14.5
  {{- if .Values.addons.metallb.values }}
  values:
{{ toYaml (fromYaml .Values.addons.metallb.values) | indent 4 }}
  {{- end }}
  defaultNamespace: "metallb-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
{{- end }}
{{- end }}