{{- if .Values.addons.monitoring }}
{{- if .Values.addons.monitoring.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-crd-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "rancher-monitoring-crd"
  repoName: "WhiteCruiser"
  releaseName: "rancher-monitoring-crd"
  version: {{ .Values.addons.monitoring.version }}
  {{- if .Values.addons.monitoring.values }}
  values:
{{ toYaml .Values.addons.monitoring.values | indent 4 }}
  {{- end }}
  defaultNamespace: "cattle-monitoring-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "rancher-monitoring"
  repoName: "WhiteCruiser"
  releaseName: "rancher-monitoring"
  version: {{ .Values.addons.monitoring.version }}
  {{- if .Values.addons.monitoring.values }}
  values:
{{ toYaml .Values.addons.monitoring.values | indent 4 }}
  {{- end }}
  defaultNamespace: "cattle-monitoring-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
  diff:
    comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: rancher-monitoring-admission
      jsonPointers:
      - /webhooks/0/failurePolicy
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: ValidatingWebhookConfiguration
      name: rancher-monitoring-admission
      jsonPointers:
      - /webhooks/0/failurePolicy
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      name: rancher-monitoring-kubelet
      namespace: kube-system
      jsonPointers:
      - /spec/endpoints
---
{{- end }}
{{- end }}
{{- if .Values.addons.metallb }}
{{- if .Values.addons.metallb.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: metallb-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "metallb"
  repoName: "whitecruiser-apps"
  releaseName: "metallb"
  version: 0.14.5
  {{- if .Values.addons.metallb.values }}
  values:
{{ toYaml .Values.addons.metallb.values | indent 4 }}
  {{- end }}
  defaultNamespace: "metallb-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
{{- end }}
{{- end }}
