apiVersion: baremetal.whitestack.com/v1
kind: WhiteCruiser
metadata:
  name: whitecruiser-hector-{{ .Values.cluster.name }}
spec:
  rancherServerURL: https://whitecruiser.10.100.18.40.nip.io
  rancherApiKey: token-mgknx:wzwtlpl2t6l2nlbp4hpwxpkkw8dvh5bhtk9fwkfjz2hj2dfhbpfc76
  rancherClusterName: {{ .Values.cluster.name }}
