addons:
  metallb:
    enabled: true
    values: |-
      speaker:
        enabled: false
    version: 0.14.5
#cloudprovider: openstack
cluster:
  config:
    chartValues:
      rke2-calico:
        installation:
          calicoNetwork:
            bgp: Enabled
            ipPools:
              - cidr: 10.42.0.0/16
                disableBGPExport: true
                encapsulation: IPIP
                natOutgoing: Enabled
                nodeSelector: all()
    enableNetworkPolicy: false
    globalConfig:
      cloud_provider_name: ''
      cni: calico
      disable_cloud_controller: false
      disable_kube_proxy: false
      disable_scheduler: false
      etcd:
        disableSnapshots: true
        snapshotRetention: 5
        snapshotScheduleCron: 0 */5 * * *
      etcd_expose_metrics: false
      profile: ''
      protect_kernel_defaults: false
      secrets_encryption: false
      selinux: false
      systemDefaultRegistry: docker.io
      use_service_account_credentials: false
      write_kubeconfig_mode: 384
    localClusterAuthEndpoint:
      enabled: false
    registries:
      enabled: false
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false
    additionalManifests: |-
      ---
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: defaultpool
        namespace: metallb-system
      spec:
        addresses:
        - 30.100.16.0/21
        autoAssign: true
      ---
      apiVersion: catalog.cattle.io/v1
      kind: ClusterRepo
      metadata:
        name: extra-charts
      spec:
        gitRepo: https://github.com/Hector295/marketplace-ws.git
        gitBranch: demo/bgp
      ---
      apiVersion: crd.projectcalico.org/v1
      kind: BGPConfiguration
      metadata:
        name: default
      spec:
        asNumber: 64512
        listenPort: 179
        logSeverityScreen: Info
        nodeToNodeMeshEnabled: false
        serviceLoadBalancerIPs:
          - cidr: 30.100.16.0/21
      ---
      apiVersion: crd.projectcalico.org/v1
      kind: BGPPeer
      metadata:
        name: gobgp-peer-all-nodes
      spec:
        asNumber: 64513
        keepOriginalNextHop: false
        nodeSelector: all()
        peerIP: 10.100.16.169
    kubernetesVersion: v1.30.9+rke2r1
  name: cluster-bgp
  localClusterAuthEndpoint:
    enabled: false
cloudCredentialSecretName: cattle-global-data:cc-7msdp