baremetalNodes:
- bmcAddress: 1.2.3.4
  hostname: edge-1
  bmcCredentialsSecret: site-1-bmc-creds
  bmcProvider: ilo
  swMgmtAddress: 10.100.20.162
  swMgmtCredentialsSecret: site-1-swmgmt-creds
  roles:
    - controlplane
    - etcd
    - worker
  primaryInterface:
    name: eno1
    address: 10.100.2.152/24
    dhcpv4: no
    defaultRoute: 10.100.2.1
- bmcAddress: 1.2.3.4
  hostname: edge-2
  bmcCredentialsSecret: site-1-bmc-creds
  bmcProvider: ilo
  swMgmtAddress: 10.100.17.210
  swMgmtCredentialsSecret: site-1-swmgmt-creds
  primaryInterface:
    name: eno1
    address: 10.100.2.152/24
    dhcpv4: no
    defaultRoute: 10.100.2.1
  roles:
    - controlplane
    - etcd
    - worker
- bmcAddress: 1.2.3.4
  hostname: edge-3
  bmcCredentialsSecret: site-1-bmc-creds
  bmcProvider: ilo
  swMgmtAddress: 10.100.19.19
  swMgmtCredentialsSecret: site-1-swmgmt-creds
  primaryInterface:
    name: eno1
    address: 10.100.2.152/24
    dhcpv4: no
    defaultRoute: 10.100.2.1
  roles:
    - controlplane
    - etcd
    - worker

addons:
  kubevirt:
    enabled: true
  logging:
    enabled: true
    server: 
      address: 10.100.18.5
      port: 24224
  longhorn:
    enabled: false
  metallb:
    enabled: true
  monitoring:
    enabled: true
    version: 104.1.0+up57.0.3
    objectStorage:
      accessKey: <changeme>
      bucket: <changeme>
      endpoint: <changeme:changeme>
      secretKey: <changeme>
    thanosIngress:
      host: <changeme>      
  openebs:
    enabled: true
    version: 4.1.1
cluster:
  lbAddresses:
    - 10.100.18.80/32
  config:
    chartValues:
      rke2-calico: {}
    enableNetworkPolicy: false
    globalConfig:
      cloud_provider_name: ''
      cni: calico
      disable_cloud_controller: false
      disable_kube_proxy: false
      disable_scheduler: false
      etcd:
        disableSnapshots: true
        snapshotRetention: 5
        snapshotScheduleCron: 0 */5 * * *
      etcd_expose_metrics: false
      profile: ''
      protect_kernel_defaults: false
      secrets_encryption: false
      selinux: false
      systemDefaultRegistry: docker.io
      use_service_account_credentials: false
      write_kubeconfig_mode: 384
    localClusterAuthEndpoint:
      enabled: false
    registries:
      enabled: false
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false
    kubernetesVersion: v1.29.9+rke2r1
  name: cluster-rke2
  localClusterAuthEndpoint:
    enabled: false